CREATE SEQUENCE IF NOT EXISTS customer_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS product_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS sale_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS address_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS history_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    domain VARCHAR(255) UNIQUE,
    logo_url VARCHAR(255),
    banner_url VARCHAR(255),
    icon_url VARCHAR(255),
    mercado_pago_secret_key VARCHAR(255),
    mercado_pago_public_key VARCHAR(255),
    melhor_envio_access_token VARCHAR(255),
    melhor_envio_refresh_token VARCHAR(255),
    instagram VARCHAR(255),
    whatsapp VARCHAR(255),
    pickup_enabled BOOLEAN,
    local_delivery_enabled BOOLEAN,
    local_delivery_fee INTEGER,
    free_shipping_min_amount INTEGER,
    shipping_origin_zip VARCHAR(255),
    local_delivery_eta VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE
);

INSERT INTO roles (name)
VALUES ('ROLE_ADMIN'), ('ROLE_USER')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS customer (
    id INTEGER PRIMARY KEY DEFAULT nextval('customer_id_seq'),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    age INTEGER,
    gender VARCHAR(255),
    password VARCHAR(255),
    profile_image_id VARCHAR(255) UNIQUE,
    phone VARCHAR(255),
    cpf VARCHAR(255) NOT NULL,
    store_id BIGINT REFERENCES store(id),
    owned_store_id BIGINT REFERENCES store(id)
);

CREATE TABLE IF NOT EXISTS customer_roles (
    customer_id INTEGER NOT NULL REFERENCES customer(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (customer_id, role_id)
);

CREATE TABLE IF NOT EXISTS customer_store_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(id),
    store_id BIGINT NOT NULL REFERENCES store(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    CONSTRAINT customer_store_role_unique UNIQUE (customer_id, store_id, role_id)
);

CREATE TABLE IF NOT EXISTS address (
    id INTEGER PRIMARY KEY DEFAULT nextval('address_id_seq'),
    customer_id INTEGER REFERENCES customer(id),
    zip VARCHAR(255) NOT NULL,
    street VARCHAR(255) NOT NULL,
    number BIGINT NOT NULL,
    district VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    reference VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    path VARCHAR(255),
    store_id BIGINT NOT NULL REFERENCES store(id)
);

CREATE TABLE IF NOT EXISTS product (
    id INTEGER PRIMARY KEY DEFAULT nextval('product_id_seq'),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    original_price INTEGER NOT NULL,
    price INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    image_id VARCHAR(255) UNIQUE,
    promo INTEGER,
    store_id BIGINT REFERENCES store(id)
);

CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id VARCHAR(255) NOT NULL,
    product_id INTEGER NOT NULL REFERENCES product(id)
);

CREATE TABLE IF NOT EXISTS product_variation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES product(id),
    sku VARCHAR(255),
    price INTEGER,
    quantity INTEGER,
    promo INTEGER,
    created_at TIMESTAMP(6),
    options JSONB
);

CREATE TABLE IF NOT EXISTS sale (
    id BIGINT PRIMARY KEY DEFAULT nextval('sale_id_seq'),
    total_price DOUBLE PRECISION NOT NULL,
    sale_date TIMESTAMP(6) NOT NULL,
    customer_id INTEGER REFERENCES customer(id),
    payment_method VARCHAR(255),
    preference_id VARCHAR(255),
    payment_id VARCHAR(255),
    status VARCHAR(255),
    shipment BOOLEAN,
    store_id BIGINT REFERENCES store(id)
);

CREATE TABLE IF NOT EXISTS sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sale(id),
    product_id INTEGER NOT NULL REFERENCES product(id),
    variation_id INTEGER REFERENCES product_variation(id),
    quantity INTEGER NOT NULL,
    price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS history (
    id INTEGER PRIMARY KEY DEFAULT nextval('history_id_seq'),
    date DATE NOT NULL,
    customer_id INTEGER REFERENCES customer(id),
    product_id INTEGER REFERENCES product(id)
);

CREATE INDEX IF NOT EXISTS idx_category_store_id ON category(store_id);
CREATE INDEX IF NOT EXISTS idx_customer_store_id ON customer(store_id);
CREATE INDEX IF NOT EXISTS idx_customer_owned_store_id ON customer(owned_store_id);
CREATE INDEX IF NOT EXISTS idx_customer_store_roles_store_id ON customer_store_roles(store_id);
CREATE INDEX IF NOT EXISTS idx_product_store_id ON product(store_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variation_product_id ON product_variation(product_id);
CREATE INDEX IF NOT EXISTS idx_sale_store_id ON sale(store_id);
CREATE INDEX IF NOT EXISTS idx_sale_preference_id ON sale(preference_id);
CREATE INDEX IF NOT EXISTS idx_sale_item_sale_id ON sale_item(sale_id);
