CREATE SEQUENCE IF NOT EXISTS customer_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS product_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS sale_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS address_id_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS history_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    domain VARCHAR(255) UNIQUE,
    logo_url VARCHAR(255),
    banner_url VARCHAR(255),
    icon_url VARCHAR(255),
    mercado_pago_secret_key VARCHAR(255),
    mercado_pago_public_key VARCHAR(255),
    melhor_envio_access_token VARCHAR(255),
    melhor_envio_refresh_token VARCHAR(255),
    instagram VARCHAR(255),
    whatsapp VARCHAR(255),
    pickup_enabled BOOLEAN,
    local_delivery_enabled BOOLEAN,
    local_delivery_fee INTEGER,
    free_shipping_min_amount INTEGER,
    shipping_origin_zip VARCHAR(255),
    local_delivery_eta VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);

ALTER TABLE store ADD COLUMN IF NOT EXISTS logo_url VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS banner_url VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS icon_url VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS mercado_pago_secret_key VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS mercado_pago_public_key VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS melhor_envio_access_token VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS melhor_envio_refresh_token VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS instagram VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS whatsapp VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS pickup_enabled BOOLEAN;
ALTER TABLE store ADD COLUMN IF NOT EXISTS local_delivery_enabled BOOLEAN;
ALTER TABLE store ADD COLUMN IF NOT EXISTS local_delivery_fee INTEGER;
ALTER TABLE store ADD COLUMN IF NOT EXISTS free_shipping_min_amount INTEGER;
ALTER TABLE store ADD COLUMN IF NOT EXISTS shipping_origin_zip VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS local_delivery_eta VARCHAR(255);
ALTER TABLE store ADD COLUMN IF NOT EXISTS created_at TIMESTAMP(6);
ALTER TABLE store ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP(6);

CREATE UNIQUE INDEX IF NOT EXISTS idx_store_domain_unique
    ON store(domain)
    WHERE domain IS NOT NULL;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE
);

INSERT INTO roles (name)
VALUES ('ROLE_ADMIN'), ('ROLE_USER')
ON CONFLICT (name) DO NOTHING;

CREATE TABLE IF NOT EXISTS customer_roles (
    customer_id INTEGER NOT NULL REFERENCES customer(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY (customer_id, role_id)
);

ALTER TABLE customer ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES store(id);
ALTER TABLE customer ADD COLUMN IF NOT EXISTS owned_store_id BIGINT REFERENCES store(id);

CREATE TABLE IF NOT EXISTS customer_store_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES customer(id),
    store_id BIGINT NOT NULL REFERENCES store(id),
    role_id BIGINT NOT NULL REFERENCES roles(id),
    CONSTRAINT customer_store_role_unique UNIQUE (customer_id, store_id, role_id)
);

ALTER TABLE category ADD COLUMN IF NOT EXISTS path VARCHAR(255);
ALTER TABLE category ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES store(id);
ALTER TABLE product ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES store(id);
ALTER TABLE sale ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES store(id);
ALTER TABLE sale ADD COLUMN IF NOT EXISTS payment_id VARCHAR(255);

CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id VARCHAR(255) NOT NULL,
    product_id INTEGER NOT NULL REFERENCES product(id)
);

CREATE TABLE IF NOT EXISTS product_variation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES product(id),
    sku VARCHAR(255),
    price INTEGER,
    quantity INTEGER,
    promo INTEGER,
    created_at TIMESTAMP(6),
    options JSONB
);

CREATE TABLE IF NOT EXISTS sale_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sale(id),
    product_id INTEGER NOT NULL REFERENCES product(id),
    variation_id INTEGER REFERENCES product_variation(id),
    quantity INTEGER NOT NULL,
    price INTEGER NOT NULL
);

INSERT INTO store (
    name,
    domain,
    logo_url,
    banner_url,
    icon_url,
    mercado_pago_secret_key,
    mercado_pago_public_key,
    melhor_envio_access_token,
    melhor_envio_refresh_token,
    instagram,
    whatsapp,
    pickup_enabled,
    local_delivery_enabled,
    local_delivery_fee,
    free_shipping_min_amount,
    created_at,
    updated_at
)
SELECT
    'Amandita',
    'localhost',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    true,
    true,
    0,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM store);

UPDATE category
SET store_id = (SELECT id FROM store ORDER BY id LIMIT 1)
WHERE store_id IS NULL;

UPDATE product
SET store_id = (SELECT id FROM store ORDER BY id LIMIT 1)
WHERE store_id IS NULL;

UPDATE sale
SET store_id = (SELECT id FROM store ORDER BY id LIMIT 1)
WHERE store_id IS NULL;

UPDATE customer
SET store_id = (SELECT id FROM store ORDER BY id LIMIT 1)
WHERE store_id IS NULL;

UPDATE customer c
SET owned_store_id = c.store_id
WHERE c.owned_store_id IS NULL
  AND c.store_id IS NOT NULL
  AND EXISTS (
      SELECT 1
      FROM customer_roles cr
      JOIN roles r ON r.id = cr.role_id
      WHERE cr.customer_id = c.id
        AND r.name = 'ROLE_ADMIN'
  );

INSERT INTO customer_store_roles (customer_id, store_id, role_id)
SELECT c.id, c.store_id, r.id
FROM customer c
JOIN roles r ON r.name = 'ROLE_USER'
WHERE c.store_id IS NOT NULL
ON CONFLICT DO NOTHING;

INSERT INTO customer_store_roles (customer_id, store_id, role_id)
SELECT c.id, c.store_id, r.id
FROM customer c
JOIN roles r ON r.name = 'ROLE_ADMIN'
WHERE c.store_id IS NOT NULL
  AND EXISTS (
      SELECT 1
      FROM customer_roles cr
      JOIN roles legacy_role ON legacy_role.id = cr.role_id
      WHERE cr.customer_id = c.id
        AND legacy_role.name = 'ROLE_ADMIN'
  )
ON CONFLICT DO NOTHING;

INSERT INTO customer_store_roles (customer_id, store_id, role_id)
SELECT c.id, c.owned_store_id, r.id
FROM customer c
JOIN roles r ON r.name = 'ROLE_ADMIN'
WHERE c.owned_store_id IS NOT NULL
ON CONFLICT DO NOTHING;

ALTER TABLE category ALTER COLUMN store_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_store_email
    ON customer(store_id, lower(email))
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_owned_store_email
    ON customer(lower(email))
    WHERE owned_store_id IS NOT NULL
      AND email IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_category_store_id ON category(store_id);
CREATE INDEX IF NOT EXISTS idx_customer_store_id ON customer(store_id);
CREATE INDEX IF NOT EXISTS idx_customer_owned_store_id ON customer(owned_store_id);
CREATE INDEX IF NOT EXISTS idx_customer_store_roles_store_id ON customer_store_roles(store_id);
CREATE INDEX IF NOT EXISTS idx_product_store_id ON product(store_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_product_variation_product_id ON product_variation(product_id);
CREATE INDEX IF NOT EXISTS idx_sale_store_id ON sale(store_id);
CREATE INDEX IF NOT EXISTS idx_sale_preference_id ON sale(preference_id);
CREATE INDEX IF NOT EXISTS idx_sale_item_sale_id ON sale_item(sale_id);
