aws:
  s3:
    mock: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/amandita
    username: amandita
    password: password
  flyway:
    enabled: false

jwt:
  secret: local-test-jwt-secret-change-before-production-2026-05-29
